// Generated by CoffeeScript 1.4.0
(function() {
  var li, _i, _len, _ref;

  _ref = $(".li");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    li = _ref[_i];
    $(".div").append($(li).val());
  }

}).call(this);
