// Generated by CoffeeScript 1.4.0
(function() {
  var maketoc, toggletoc;

  maketoc = function() {
    var h3, h3list, _i, _len, _results;
    h3list = $(".entry h3");
    if (h3list.length === 0) {
      return $(".table-of-contents").hide();
    } else {
      _results = [];
      for (_i = 0, _len = h3list.length; _i < _len; _i++) {
        h3 = h3list[_i];
        _results.push($("#toc").append("<li><a href='#" + $(h3).attr("id") + "'>" + $(h3).text() + "</a></li>"));
      }
      return _results;
    }
  };

  toggletoc = function() {
    var icon, toc;
    toc = $("#toc");
    icon = $("#toggle-icon");
    if (toc.is(":visible")) {
      icon.removeClass("fa-minus-circle").addClass("fa-plus-circle");
      return toc.hide();
    } else {
      icon.removeClass("fa-plus-circle").addClass("fa-minus-circle");
      return toc.show();
    }
  };

  $(function() {
    var _this = this;
    maketoc();
    $("nav.table-of-contents h5").click(function() {
      return toggletoc();
    });
    return $("#toc").hide();
  });

}).call(this);
